### ISSUE TITLE
`InternalServerError` with EnhancedDateTimePicker 2.0.2 and Vaadin 21.0.2

### ISSUE THREAD

**Issue by McPringle** [vaadin-component-factory/enhanced-date-time-picker#7]
This time I'm running a Vaadin 21.0.2 app on Windows 10 and get the below error on startup. Without this component, the app starts and displays fine.

```
<dependency>
    <groupId>org.vaadin.addons.componentfactory</groupId>
    <artifactId>enhanced-date-time-picker</artifactId>
    <version>2.0.2</version>
</dependency>
```

```
There was an unexpected error (type=Internal Server Error, status=500).
java.lang.IllegalStateException: Failed to find the following files: - ./enhancedTimepickerConnector.js Locations searched were: - `C:\Users\*****\IdeaProjects\komunumo-server\.\frontend` in this project - `META-INF/frontend` in included JARs Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
com.vaadin.flow.server.ServiceException: java.lang.IllegalStateException: 

  Failed to find the following files: 
      - ./enhancedTimepickerConnector.js
  
  Locations searched were:
      - `C:\Users\*****\IdeaProjects\komunumo-server\.\frontend` in this project
      - `META-INF/frontend` in included JARs

  Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)

	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getUniqueEs6ImportPaths(AbstractUpdateImports.java:385) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getModuleLines(AbstractUpdateImports.java:398) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.collectModules(AbstractUpdateImports.java:311) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:115) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:369) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:762) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:499) ~[vaadin-dev-server-8.0.2.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:387) ~[vaadin-dev-server-8.0.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1736) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

I tried a `mvnw clean` and deleted the `node_modules` to force a clean build, without success.

**Comment by McPringle** [comment]
Additional info: version 2.0.1 works fine!

**Comment by McPringle** [comment]
I created a minimal project with only one view and only this component to show the error:
https://github.com/McPringle/vaadin21-enhanceddatetimepicker

**Comment by paodb** [comment]
Hello. Thanks for reporting this. I just did a checkout of your project and it's working okay. Also tested it in a sampler project of mine and couldn't reproduce the mentioned error either. Maybe you could try the [Vaadin Dance](https://mvysny.github.io/Vaadin-troubleshooting/#the-vaadin-dance ) on your project to get rid of any wrong updates.

**Comment by McPringle** [comment]
Hi @paodb, never heard of the Vaadin Dance before. Thanks for pointing at it, it might be useful for other problems. I tried the Vaadin Dance with my test project, still the same error - but the message changed slightly. On my first attempt, I got the above-mentioned error message on the first request to the view. After the Vaadin Dance, I get the message while starting the server (while running the Maven task `vaadin:build-frontend`):

```
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve './enhancedTimepickerConnector.js' in 'C:\Users\McPringle\IdeaProjects\vaadin21-enhanceddatetimepicker\target\frontend'
```

Followed by a `NPE`:

```
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.Lock.lock()" because the return value of "com.vaadin.flow.server.VaadinSession.getLockInstance()" is null
	at com.vaadin.flow.server.VaadinSession.lock(VaadinSession.java:685) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:212) ~[flow-server-8.0.2.jar:8.0.2]
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1860) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:861) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:660) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:608) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:591) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5622) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1365) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1347) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.53.jar:9.0.53]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:an]
```

I'm running this on Windows (latest patch level) within IntelliJ IDEA (latest version) if it might be important.

**Comment by McPringle** [comment]
I made another test. This time I went to `start.vaadin.com` and created a Flow app with Vaadin 21, Java 11, and one empty view. I downloaded and extracted the project, opened it within IntelliJ IDEA, and started it: Everything is working fine.

Then I added the dependency for `EnhancedDateTimePicker` version 2.0.2 to the `pom.xml` and to the view. Now it crashes while starting with the error message mentioned in my report. I can reproduce this every time, even when I start with a new and empty project.
